### ISSUE TITLE
symmetric coroutine

### ISSUE THREAD

**Issue by sharow** [sharow/libconcurrent#13]
TBD

**Comment by mitghi** [comment]
Please add some description for this task :)

**Comment by sharow** [comment]
hmm.. let me think a moment.

at first grance, this makes confusion about the symmetric/asymmetric both context.
maybe this should be another project.
or user can implement symmetric style coroutine(switch_to()) on top of libconcurrent.
I think this is why abandon this task. actually I can't remember why I'm put this task. 🤔
