### ISSUE TITLE
error compile on mac

### ISSUE THREAD

**Issue by i5ting** [sharow/libconcurrent#9]
```
➜  libconcurrent git:(master) make   
uname: illegal option -- o
usage: uname [-amnprsv]
uname: illegal option -- o
usage: uname [-amnprsv]
uname: illegal option -- o
usage: uname [-amnprsv]
uname: illegal option -- o
usage: uname [-amnprsv]
nasm  -f elf64 src/arch/x86_64/concurrent_arch.asm -o src/arch/x86_64/concurrent_arch.o
nasm: fatal: unrecognised output format `elf64' - use -hf for a list
type `nasm -h' for help
make: *** [src/arch/x86_64/concurrent_arch.o] Error 1
```

**Comment by sharow** [comment]
libconcurrent is not support OSX.
even if `uname` stuff solve, still fail.
OSX(64bit) calling convention is different from others.

https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/LowLevelABI/140-x86-64_Function_Calling_Conventions/x86_64.html#//apple_ref/doc/uid/TP40005035-SW1

( but I'm keeping open this issue for now )
